### ISSUE TITLE
Portfolio review/comments

### ISSUE THREAD

**Issue by LouisaBarrett** [swanie21/swanie21.github.io#1]
Design:
- Well structured, clear content sections, and thoughtful writing.
- You're using a lovely font pairing in your "About" section, but you're using a completely different and unrelated pair of fonts that do not pair well together in your hero/landing section. The fonts used in the "About" section are easier to read and show better typography usage, I would suggest using those throughout the site exclusively.
- Nice responsive layout! Nitpick: In the hero section, the `.rotating-words` crowds the block of copy below it as it changes. On smaller screens, it might also be worth making the height of your hero section shorter, so you don't have to scroll so far before you get to the about content.
- In the "Portfolio" section, some of the images your using are being smooshed a bit. Make sure you're either using square images or cropping/sizing them with CSS in a way that doesn't squish your images.
- I'd include a link to the github repos of your project, since it's likely that a good amount of traffic to your site will be prospective employers/technical people who want to take a look at your code.

*Overall, it's looking good! It needs fine tuning but you're in a solid place to take it to the next level.

HTML:
- In your `.intro` section, you have a collection of `<span>` tags nested within an `<h2>` with a `<div>` nested that contains your `.rotating-words`. This is a little funky. I'd suggest only having the "Who am I?" copy in the `<h2>` and moving the rotating words into a `<ul>` with each phrase as an `<li>`, and then within each `<li>` you can have the appropriate header tag you'd like to use.
- Within the `<section>` tags you're using for the "About" and "Portfolio" sections, I would probably use something like an `<article>` rather that `<div>` tags.

CSS:
- nice use of CSS animations! 🎉 
- be consistent with how you organize the declarations within each CSS rule.
- good use of comments to clarify which css rules are for which content

**Comment by swanie21** [comment]
Hi Louisa,

Thank you for your thorough and thoughtful feedback. I will definitely
implement your suggestions. I noticed how the images are squished earlier
and I tried to resize them, but wasn't able to successfully. I tried to
resize them in Sketch, but the image resolution became distorted. How can I
successfully resize the images? Thanks for your help in advance!

~Kirsten
